[app]
    appEnv                = "default"
    serviceName           = "SetuApp"
    hostname              = "api.setu.com"
    shutdownTimeout       = 2
    shutdownDelay         = 2
    gitCommitHash         = "nil"
    [app.interfaces]
        [app.interfaces.service]
            GrpcServerAddress = "0.0.0.0:8080"
            HttpServerAddress = "0.0.0.0:8081"
            InternalServerAddress = "0.0.0.0:8082"

[db]
    Username    ="root"
    Password    ="1234"
    Host        ="localhost"
    Port        ="3306"
    DBName      ="invoice"
    Charset     ="utf8mb4"