[app]
    appEnv                = "default"
    serviceName           = "SetuApp"
    hostname              = "api.setu.com"
    shutdownTimeout       = 2
    shutdownDelay         = 2
    gitCommitHash         = "nil"
    [app.interfaces]
        [app.interfaces.service]
            GrpcServerAddress = "0.0.0.0:8080"
            HttpServerAddress = "0.0.0.0:8081"
            InternalServerAddress = "0.0.0.0:8082"

[db]
    Username    ="root"
    Password    ="1234"
    Host        ="localhost"
    Port        ="3306"
    DBName      ="invoice"
    Charset     ="utf8mb4"

[SetuGatewayService]
    mock = false
    BaseUrl = "https://dg-sandbox.setu.co"
    [SetuGatewayService.ValidatePAN]
        path = "/api/verify/pan"
        method = "POST"
        [SetuGatewayService.ValidatePAN.Headers]
            x-client-id="test-client"
            x-client-secret="891707ee-d6cd-4744-a28d-058829e30f12"
            x-product-instance-id="891707ee-d6cd-4744-a28d-058829e30f10"
    [SetuGatewayService.Auth]
        username = ""
        password = ""
    [SetuGatewayService.HystrixResiliencyConfig]
        MaxConcurrentRequests = 100
        RequestVolumeThreshold = 20
        CircuitBreakerSleepWindow = 5000
        ErrorPercentThreshold = 50
        CircuitBreakerTimeout = 10000
    [SetuGatewayService.ConnPoolConfig]
        Timeout                             = 10000
        KeepAliveTimeout                    = 90000
        MaxIdleConnections                  = 30
        SkipCertVerification                = false